services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    user: '1000:1000'
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
