services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: money
      POSTGRES_USER: moneyuser
      POSTGRES_PASSWORD: moneypass
    ports:
      - '5432:5432'

volumes:
  db_data:
