# Generated by Django 4.2.3 on 2023-07-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contragent',
            new_name='Counterparty',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='contragent',
            new_name='counterparty',
        ),
    ]
