# Generated by Django 4.2.3 on 2023-07-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_transaction_counterparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
