# Generated by Django 4.2 on 2023-07-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_setting_alter_operation_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='sum',
            new_name='amount',
        ),
    ]
