# Generated by Django 4.2 on 2023-07-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_sum_operation_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='sum',
        ),
        migrations.AddField(
            model_name='plan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
