# Generated by Django 4.2 on 2023-08-01 19:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_plan_sum_plan_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', app.models.CurrencyField(choices=[('RUB', 'Russian Ruble'), ('GEL', 'Georgian Lari'), ('USD', 'US Dollar')], max_length=3)),
                ('base_currency', app.models.CurrencyField(choices=[('RUB', 'Russian Ruble'), ('GEL', 'Georgian Lari'), ('USD', 'US Dollar')], max_length=3)),
                ('date', models.DateTimeField()),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=app.models.CurrencyField(choices=[('RUB', 'Russian Ruble'), ('GEL', 'Georgian Lari'), ('USD', 'US Dollar')], max_length=3),
        ),
    ]
