# Generated by Django 4.2 on 2023-09-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_currencyrate_alter_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operations', to='app.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.category'),
        ),
    ]
